version: '3.9'
services:
  app1: &app
    image: apache-php:0.0.1
    build:
      context: .
  app2:
    <<: *app
  app3:
    <<: *app
  app4:
    <<: *app

  loadbalancer:
    image: nginx:1.25-bookworm
    ports:
      - 80:80
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
